### ISSUE TITLE
the api website has hosting issues

### ISSUE THREAD

**Issue by Saizuo** [moyshik7/shiro.gg#1]
Hey there the api is having an issue as the webserver isnt hosted anymore or has some issues with configuration , any estimated time on fix would be great 🙏🏻

**Comment by moyshik7** [comment]
Well according to the official news the api will completely shut down after 30 days.  
any update now (from shiro.gg/api to api.shiro.gg) will be pretty much useless.  
Thanks for understanding

**Comment by Saizuo** [comment]
ah this really is sad, tho I been using it on my discord bot for sometime, it really worked well and I respect the Owners of the api, thx for informing too!
